### ISSUE TITLE
spades test data doesnot work with me with following output

### ISSUE THREAD

**Issue by Sabrin2020** [ablab/spades#1024]
### Description of bug

(spades-env) [asga9989@hpcl002 ~]$ spades.py --test
Command line: /user/asga9989/.conda/envs/spades-env/bin/spades.py       --test

System information:
  SPAdes version: 3.13.0
  Python version: 3.10.4
  OS: Linux-3.10.0-514.el7.x86_64-x86_64-with-glibc2.17

Output dir: /user/asga9989/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
Traceback (most recent call last):
  File "/user/asga9989/.conda/envs/spades-env/bin/spades.py", line 1093, in <module>
    main(sys.argv)
  File "/user/asga9989/.conda/envs/spades-env/bin/spades.py", line 714, in main
    print_used_values(cfg, log)
  File "/user/asga9989/.conda/envs/spades-env/bin/spades.py", line 110, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename, 'r'))
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/user/asga9989/.conda/envs/spades-env/share/spades-3.13.0-0/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

### spades.log

Command line: /user/asga9989/.conda/envs/spades-env/bin/spades.py       --test

System information:
  SPAdes version: 3.13.0
  Python version: 3.10.4
  OS: Linux-3.10.0-514.el7.x86_64-x86_64-with-glibc2.17

Output dir: /user/asga9989/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:

### params.txt

Command line: /user/asga9989/.conda/envs/spades-env/bin/spades.py       --test

System information:
  SPAdes version: 3.13.0
  Python version: 3.10.4
  OS: Linux-3.10.0-514.el7.x86_64-x86_64-with-glibc2.17

Output dir: /user/asga9989/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:

### SPAdes version

 SPAdes version: 3.13.0

### Operating System

OS: Linux-3.10.0-514.el7.x86_64-x86_64-with-glibc2.17

### Python Version

 Python version: 3.10.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by Sabrin2020** [comment]
How can i please make test data work to proceed with my data with spades?

**Comment by asl** [comment]
Please upgrade to the latest SPAdes 3.15.5.
