### ISSUE TITLE
SPAdes 3.15.5 ERROR in MacOS Monterey:  == Error ==  exception caught: <class 'FileNotFoundError'> 

### ISSUE THREAD

**Issue by YuLanSky** [ablab/spades#1153]
### Description of bug

This is an issue that only occurs in SPAdes 3.15.5, if I use SPAdes 3.15.4, this problem goes away. 
It is just a very common assembly work of Enterobacteriaceae bacterial WNGS data. 
The command line reads something like:
```
spades.py -1 file_1.fq -2 file_2.fq --isolate -o merge 
```
I seem to be able to get the contig.fasta file I want, but the program ends up reporting the following bug:
```
[Errno 2] No such file or directory: '._config.info'
Traceback (most recent call last):
  File "/Users/chuchuli/opt/SPAdes-3.15.5-Darwin/bin/spades.py", line 634, in main
    executor.execute(commands)
  File "/Users/chuchuli/opt/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/executors/executor_local.py", line 39, in execute
    self.rm_files(command)
  File "/Users/chuchuli/opt/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/executors/executor_local.py", line 62, in rm_files
    shutil.rmtree(fpath_abs)
  File "/Users/chuchuli/miniconda3/lib/python3.10/shutil.py", line 724, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/chuchuli/miniconda3/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/Users/chuchuli/miniconda3/lib/python3.10/shutil.py", line 680, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Users/chuchuli/miniconda3/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '._config.info'
```
This bug only caused my ‘xargs’ function not run properly to the next one, no other effects have been found yet.
Finally, I have to say that the software you guys made is really awesome!

### spades.log

[spades.log](https://github.com/ablab/spades/files/11880459/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11880475/params.txt)

### SPAdes version

SPAdes 3.15.5

### Operating System

macOS Monterey 12.6.6

### Python Version

Python 3.11.0

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This seems to be some mac os specific I/O problem. Likely related to the external volume used.

**Comment by YuLanSky** [comment]
> This seems to be some mac os specific I/O problem. Likely related to the external volume used.

The problem is sort of solved. I retried it and it does have something to do with external disks. But the same problem does appear only in 3.15.5, but not in 3.15.4
