### ISSUE TITLE
Running spades on M1 Mac in iTerm set to Rossetta

### ISSUE THREAD

**Issue by peflanag** [ablab/spades#1165]
### Description of bug

Hi, I have an iTerm terminal set to rossetta so I can run Conda and Conda environments. I installed spades and it seems ok but when I run it I get the following error. Im a microbiologist and command line is more self thought so I'm not sure what the error means.

Cheers

(spades) drflanman@Peters-MacBook-Air-4 Scripts % ./SPAdes_Script.sh
Command line: /Users/drflanman/miniconda3/envs/spades/bin/spades.py	--isolate	-1	/Users/drflanman/Documents/Work/HSE/Research/Connolly_OB/Fastp_output/22S-3269_L001_R1.fastq.gz	-2	/Users/drflanman/Documents/Work/HSE/Research/Connolly_OB/Fastp_output/22S-3269_L001_R2.fastq.gz	-o	/Users/drflanman/Documents/Work/HSE/Research/Connolly_OB/Spades/22S-3269

System information:
  SPAdes version: 3.15.2
  Python version: 3.11.4
  OS: macOS-13.5-x86_64-i386-64bit

Output dir: /Users/drflanman/Documents/Work/HSE/Research/Connolly_OB/Spades/22S-3269
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Isolate mode
  Reads:
Traceback (most recent call last):
  File "/Users/drflanman/miniconda3/envs/spades/bin/spades.py", line 651, in <module>
    main(sys.argv)
  File "/Users/drflanman/miniconda3/envs/spades/bin/spades.py", line 591, in main
    print_params(log, log_filename, command_line, args, cfg)
  File "/Users/drflanman/miniconda3/envs/spades/bin/spades.py", line 327, in print_params
    print_used_values(cfg, log)
  File "/Users/drflanman/miniconda3/envs/spades/bin/spades.py", line 117, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drflanman/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Hashable'

### spades.log

[spades.log](https://github.com/ablab/spades/files/12367072/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12367075/params.txt)

### SPAdes version

3.15.2

### Operating System

macOS Ventura 13.5

### Python Version

3.11.4

### Method of SPAdes installation

conda 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This was the issue fixes in SPAdes 3.15.3. Consider upgrading to the latest SPAdes 3.15.5

**Comment by peflanag** [comment]
@asl Sorry I didn't realise I was on an older version! I installed by Conda install and assumed it was the up to date version! Cheers!

**Comment by asl** [comment]
@peflanag Conda should have 3.15.5: https://anaconda.org/bioconda/spades For some reason they did not update macosx binaries (we do not maintain those). You can grab the binaries from https://github.com/ablab/spades/releases/tag/v3.15.5

**Comment by peflanag** [comment]
You're a star! Cheers!
