### ISSUE TITLE
How to use spades operate a fasta file, especially simulated reads in fasta format from badread?

### ISSUE THREAD

**Issue by SoSongzhi** [ablab/spades#1305]
### Description of bug

(bio) zhisong@zhisongs-MacBook-Air spades % bin/spades.py -s ../accuvirnew/bad_nano/hiv_50_2k.fastq -o testfasta --isolate

== Error ==  /Users/zhisong/Desktop/accuvirnew/bad_nano/hiv_50_2k.fastq is not a valid FASTQ file

Traceback (most recent call last):
  File "/Users/zhisong/Desktop/spades/share/spades/spades_pipeline/support.py", line 146, in check_file_not_empty
    if next(reads_iterator, None) is None:
  File "/Users/zhisong/Desktop/spades/share/spades/spades_pipeline/common/SeqIO.py", line 123, in parse_fastq
    raise Exception("/Users/zhisong/Desktop/accuvirnew/bad_nano/hiv_50_2k.fastq is not a valid FASTQ file")
Exception: /Users/zhisong/Desktop/accuvirnew/bad_nano/hiv_50_2k.fastq is not a valid FASTQ file

In case you have troubles running SPAdes, you can report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

### spades.log

no log

### params.txt

 bin/spades.py -s ../accuvirnew/bad_nano/hiv_50_2k.fastq -o testfasta --isolate

### SPAdes version

Spades 3.16.0-dev

### Operating System

macOS Ventura version 13.6

### Python Version

python 3.8.4

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Will you please attach the input file? Per error message – it is not a valid FASTQ file

**Comment by SoSongzhi** [comment]
thank you for your reply. the input is like this:
<img width="1365" alt="image" src="https://github.com/ablab/spades/assets/74604653/2ba52c10-1a6d-4cf2-806b-89f2c213024c">

**Comment by asl** [comment]
Please attach the file itself

**Comment by SoSongzhi** [comment]
ok, thank you so much.
[hiv_50_2k.fastq.zip](https://github.com/ablab/spades/files/15409994/hiv_50_2k.fastq.zip)

**Comment by asl** [comment]
I cannot reproduce the problem, everything is ok for me. So, likely there is some local problem. In any case, these reads are not valid SPAdes input as Illumina reads cannot be that long.

**Comment by asl** [comment]
Per SPAdes manual (https://ablab.github.io/spades/input.html):

To run SPAdes you need at least one library of the following types:
- Illumina paired-end/high-quality mate-pairs/unpaired reads
- IonTorrent paired-end/high-quality mate-pairs/unpaired reads
- PacBio CCS reads

Illumina and IonTorrent libraries should not be assembled together. All other types of input data are compatible. SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available.

**Comment by SoSongzhi** [comment]
thanks so much.
