### ISSUE TITLE
Errno5. Spades assembly error

### ISSUE THREAD

**Issue by jtahir** [ablab/spades#136]
Hi
We have been running Spades assembly on a cluster 
It ran for 48 hrs and generated corrected p.e reads. However as the assembler kicked off it gave an error and stopped. Following are the errors and input command. Please advise, thanks 

input command
bsub -e spades_output.err -o spades_output.out spades.py --pe1-1 /workspace/cfphxd/bioinf_xx/004.Data.gt81/XX_L001_trimmed_R1.fastq.gz --pe1-2 /workspace/cfphxd/bioinf_xx/004.Data.gt81/XX_L001_trimmed_R2.fastq.gz \
-k 81 -t 16 -m 128 -o spades_output

sapdes_output 
===== Assembling started.

== Running assembler: K81

[Errno 5] Input/output error
Traceback (most recent call last):
  File "/software/bioinformatics/SPAdes-3.11.1/bin/spades.py", line 832, in main
  File "/software/bioinformatics/SPAdes-3.11.1/share/spades/spades_pipeline/spades_logic.py", line 306, in run_spades
  File "/software/bioinformatics/SPAdes-3.11.1/share/spades/spades_pipeline/spades_logic.py", line 213, in run_iteration
  File "/software/bioinformatics/SPAdes-3.11.1/share/spades/spades_pipeline/support.py", line 243, in sys_call
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 5] Input/output error

== Error ==  exception caught: <type 'exceptions.OSError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by asl** [comment]
The log reads:

```OSError: [Errno 5] Input/output error```

So, the was an I/O problem on your cluster. I would suggest to contact your system administrator for more information about this.
