### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by daidiy1109** [ablab/spades#1364]
### Description of bug

AttributeError: 'dict' object has no attribute 'add'

### spades.log

[spades (1).log](https://github.com/user-attachments/files/16844539/spades.1.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16844538/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.17

### Python Version

  Python version: 3.8.19

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by daidiy1109** [comment]
run --test, laso appear the same problem.
'dict' object has no attribute 'add'
Traceback (most recent call last):
  File "/public5/home/t6s000894/.conda/envs/spades/bin/spades.py", line 874, in main
    used_K = spades_logic.run_spades(tmp_configs_dir, bin_home, spades_cfg, dataset_data, ext_python_modules_home, log)
  File "/public5/home/t6s000894/.conda/envs/spades/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 311, in run_spades
    run_iteration(configs_dir, execution_home, cfg, log, K, None, False)
  File "/public5/home/t6s000894/.conda/envs/spades/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 188, in run_iteration
    dir_util.copy_tree(os.path.join(configs_dir, "debruijn"), dst_configs, preserve_times=False)
  File "/public5/home/t6s000894/.conda/envs/spades/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 146, in copy_tree
    mkpath(dst, verbose=verbose)
  File "/public5/home/t6s000894/.conda/envs/spades/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 82, in mkpath
    _path_created.add(abs_head)
AttributeError: 'dict' object has no attribute 'add'

**Comment by asl** [comment]
You are using ancient SPAdes 3.13.0. Consider upgrading to the latest SPAdes 4.0
