### ISSUE TITLE
metaspades - number of errors on not found files

### ISSUE THREAD

**Issue by GeoMicroSoares** [ablab/spades#202]
Hi there,
Running spades on an HPC and am getting the following error in ca. 1min after the submission:
```
[user@sl2 metaspades_assembly]$ cat bench.out.28552 
Command line: /opt/SPAdes-3.13.0-Linux/bin/spades.py	--meta	-k	21,33,55,77,99,127	--tmp-dir	/scratch/user	-o	/home/user/metagenomes/data/analysis/assembly/metaspades_assembly	-1	/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_004_S4_trimqc_R1_001.fastq.gz	-2	/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_004_S4_trimqc_R2_001.fastq.gz	

System information:
  SPAdes version: 3.13.0
  Python version: 2.7.15
  OS: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic

Output dir: /home/user/metagenomes/data/analysis/assembly/metaspades_assembly
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_004_S4_trimqc_R1_001.fastq.gz']
      right reads: ['/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_004_S4_trimqc_R2_001.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77, 99, 127]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/user
  Threads: 16
  Memory limit (in Gb): 250


======= SPAdes pipeline started. Log can be found here: /home/user/metagenomes/data/analysis/assembly/metaspades_assembly/spades.log

[Errno 2] No such file or directory: '/home/user/metagenomes/data/analysis/assembly/metaspades_assembly/configs/corrector/corrector.info'
Traceback (most recent call last):
  File "/opt/SPAdes-3.13.0-Linux/bin/spades.py", line 756, in main
    dir_util.copy_tree(os.path.join(spades_home, "configs"), tmp_configs_dir, preserve_times=False, preserve_mode=False)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 156, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib/python2.7/distutils/file_util.py", line 44, in _copy_file_contents
    fdst = open(dst, 'wb')
IOError: [Errno 2] No such file or directory: '/home/user/metagenomes/data/analysis/assembly/metaspades_assembly/configs/corrector/corrector.info'


== Error ==  exception caught: <type 'exceptions.IOError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
Command line: /opt/SPAdes-3.13.0-Linux/bin/spades.py	--meta	-k	21,33,55,77,99,127	--tmp-dir	/scratch/user	-o	/home/user/metagenomes/data/analysis/assembly/metaspades_assembly	-1	/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_007_S7_trimqc_R1_001.fastq.gz	-2	/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_007_S7_trimqc_R2_001.fastq.gz	

System information:
  SPAdes version: 3.13.0
  Python version: 2.7.15
  OS: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic

Output dir: /home/user/metagenomes/data/analysis/assembly/metaspades_assembly
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_007_S7_trimqc_R1_001.fastq.gz']
      right reads: ['/home/user/metagenomes/data/analysis/qc_trimmed_data/S117_M_007_S7_trimqc_R2_001.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77, 99, 127]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/user
  Threads: 16
  Memory limit (in Gb): 250


======= SPAdes pipeline started. Log can be found here: /home/user/metagenomes/data/analysis/assembly/metaspades_assembly/spades.log

[Errno 39] Directory not empty: '/home/user/metagenomes/data/analysis/assembly/metaspades_assembly/configs/debruijn'
Traceback (most recent call last):
  File "/opt/SPAdes-3.13.0-Linux/bin/spades.py", line 751, in main
    shutil.rmtree(tmp_configs_dir)
  File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 268, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/user/metagenomes/data/analysis/assembly/metaspades_assembly/configs/debruijn'


== Error ==  exception caught: <type 'exceptions.OSError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
```
I'm not sure why this is happening, what more information can I provide to get to the bottom of this?

Thanks!

**Comment by asl** [comment]
Hello

I suspect there are some I/O errors on your HPC. Make sure that you have permissions to write files, etc.

**Comment by GeoMicroSoares** [comment]
Hi @asl I do, just checked...

**Comment by asl** [comment]
According to the logs now everything is up and running.

**Comment by GeoMicroSoares** [comment]
Yes @asl , but those three are output on the same run though and metaspades just stops. Weird?

**Comment by asl** [comment]
Well, not at all. We saw lots of various issues on network-attaches storages, including race conditions, incomplete writes, etc. that happens from time to time. I suspect you're seeing something similar here.

Can it be possible that you run two instances somehow that would use the same output directory?

**Comment by GeoMicroSoares** [comment]
It ended up being exactly that, output was being overwritten over and over. Thanks for the help!
