### ISSUE TITLE
multiple single-end libraries assembly

### ISSUE THREAD

**Issue by alienzj** [ablab/spades#211]
Hello, great spades developer, please help me~
s__Anaeroglobus_geminatus.yaml: 
```
{
    type: single,
    single reads: [
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086609.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060824.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086632.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086612.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060752.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060797.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043161.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043162.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043163.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043164.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043165.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043167.noHomo.fq.gz,
        /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043168.noHomo.fq.gz
    ]
}
```
```
spades.py --dataset s__Anaeroglobus_geminatus.yaml -o s__Anaeroglobus_geminatus.spades_out --threads 8 --memory 30
```
get error:
```
Traceback (most recent call last):
File "/ldfssz1/ST_META/share/User/zhujie/bioenv/bin/spades.py", line 1073, in <module>
main(sys.argv)
File "/ldfssz1/ST_META/share/User/zhujie/bioenv/bin/spades.py", line 623, in main
cfg, dataset_data = fill_cfg(options, log)
File "/ldfssz1/ST_META/share/User/zhujie/bioenv/bin/spades.py", line 430, in fill_cfg
dataset_data = support.relative2abs_paths(dataset_data, os.path.dirname(options_storage.dataset_yaml_filename))
File "/ldfssz1/ST_META/share/User/zhujie/bioenv/share/spades-3.12.0-1/share/spades/spades_pipeline/support.py", line 593, in relative2abs_paths
for key, value in reads_library.items():
AttributeError: 'str' object has no attribute 'items'
```
Help me, please~

**Comment by alienzj** [comment]
If format like bellow, it worked.
```
[
    {
        type: single,
        single reads: [
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086609.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060824.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086632.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17086612.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060752.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17060797.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043161.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043162.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043163.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043164.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043165.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043167.noHomo.fq.gz,
            /hwfssz1/ST_META/F12ZOOYJSY1142_FGT_CC/hll/Data_Genital/Genital_2017/RSZYD17043168.noHomo.fq.gz
        ]
    }
]
```
