### ISSUE TITLE
rnaspades.py 3.11 "AssertionError" for Python 3.*

### ISSUE THREAD

**Issue by npavlovikj** [ablab/spades#28]
Hi,

I just downloaded "SPAdes-3.11.0-Linux.tar.gz", and when I try and test the binaries, for "rnaspades.py" and Python 3.2, 3.3, 3.4, 3.5 and 3.6 I get the following error:
**$ ./rnaspades.py --test**
Traceback (most recent call last):
  File "./rnaspades.py", line 1043, in <module>
    main(sys.argv)
  File "./rnaspades.py", line 609, in main
    cfg, dataset_data = fill_cfg(options, log)
  File "./rnaspades.py", line 484, in fill_cfg
    k_value = support.get_reads_length(dataset_data, log) / 2 - 1
  File "/home/centos/install/SPAdes-3.11.0-Linux/share/spades/spades_pipeline/support.py", line 607, in get_reads_length
    max_reads_lenghts = [get_max_reads_length(reads_file, log, num_checked) for reads_file in get_reads_files(dataset_data)]
  File "/home/centos/install/SPAdes-3.11.0-Linux/share/spades/spades_pipeline/support.py", line 607, in <listcomp>
    max_reads_lenghts = [get_max_reads_length(reads_file, log, num_checked) for reads_file in get_reads_files(dataset_data)]
  File "/home/centos/install/SPAdes-3.11.0-Linux/share/spades/spades_pipeline/support.py", line 631, in get_max_reads_length
    max_reads_length = max([len(rec) for rec in itertools.islice(SeqIO.parse(SeqIO.Open(reads_file, "r"), file_type), num_checked)])
  File "/home/centos/install/SPAdes-3.11.0-Linux/share/spades/spades_pipeline/support.py", line 631, in <listcomp>
    max_reads_length = max([len(rec) for rec in itertools.islice(SeqIO.parse(SeqIO.Open(reads_file, "r"), file_type), num_checked)])
  File "/home/centos/install/SPAdes-3.11.0-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 113, in parse_fastq
    assert(rec_id[0] == '@')
AssertionError

The same error occurs when I compile SPAdes 3.11 from the source code.
However, both the binary and the source code work fine with Python 2.6 and Python 2.7.

Can you please help me resolve this issue ?

Thank you,
Natasha

**Comment by asl** [comment]
Fixed in 3.11.1
