### ISSUE TITLE
truspades.py --version gives error

### ISSUE THREAD

**Issue by notestaff** [ablab/spades#417]
(master_env_v164_py36) 16:58  [SPAdes-3.14.0] $ ./truspades.py --version
Traceback (most recent call last):
  File "./truspades.py", line 191, in <module>
    main(sys.argv)
  File "./truspades.py", line 159, in main
    options = launch_options.Options(argv, spades_home, truspades_home, spades_version)
  File "/data/sw/SPAdes-3.14.0/src/spades_pipeline/truspades/launch_options.py", line 53, in __init__
    print_version_and_exit(self.version)
  File "/data/sw/SPAdes-3.14.0/src/spades_pipeline/truspades/launch_options.py", line 141, in print_version_and_exit
    options_storage.version(version, mode="tru")
AttributeError: module 'options_storage' has no attribute 'version'

**Comment by asl** [comment]
Thanks! We will either fix this in 3.15 or deprecate truSPAdes finally after all :)

**Comment by asl** [comment]
Fix will be included into 3.15
