### ISSUE TITLE
AssertionError  assert (cnt == buf_size)

### ISSUE THREAD

**Issue by Rhinogradentia** [ablab/spades#455]
Hi,
I'm trying to run spades on metagenomic data (Illumina NovaSeq PE50) and run into the following error:

spades.log
```
Command line: /usr/local/bin/SPAdes-3.14.0-Linux/bin//spades.py -o      /scratch/users/nadine/assembly/spades      --meta  --pe1-1 /scratch/users/nadine/assembly/HHLYTDRXX_113813_1_repaired.fq      --pe1-2 /scratch/users/nadine/assembly/HHLYTDRXX_113813_2_repaired.fq      --pe1-s /scratch/users/nadine/assembly/singletons.fq       --only-assembler        

System information:
  SPAdes version: 3.14.0
  Python version: 2.7.17
  OS: Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic

Output dir: /scratch/users/nadine/assembly/spades
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/scratch/users/nadine/assembly/HHLYTDRXX_113813_1_repaired.fq']
      right reads: ['/scratch/users/nadine/assembly/HHLYTDRXX_113813_2_repaired.fq']
      interlaced reads: not specified
      single reads: ['/scratch/users/nadine/assembly/singletons.fq']
      merged reads: not specified
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch-cbe/users/nadine.tatto/alexv_meta/assembly/spades/tmp
  Threads: 16
  Memory limit (in Gb): 169


======= SPAdes pipeline started. Log can be found here: /scratch/users/nadine/assembly/spades/spades.log

/scratch/users/nadine/assembly/HHLYTDRXX_113813_2_repaired.fq: max reads length: 50
/scratch/users/nadine/assembly/HHLYTDRXX_113813_1_repaired.fq: max reads length: 50

Traceback (most recent call last):
  File "/usr/local/bin/SPAdes-3.14.0-Linux/bin//spades.py", line 590, in main
    bin_home, ext_python_modules_home, python_modules_home)
  File "/usr/local/bin/SPAdes-3.14.0-Linux/bin//spades.py", line 530, in build_pipeline
    ext_python_modules_home, python_modules_home)
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 378, in add_to_pipeline
    dataset_data, log, bin_home, ext_python_modules_home, python_modules_home))
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 286, in __init__
    generateK(self.cfg, self.log, self.dataset_data)
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 122, in generateK
    options_storage.READS_TYPES_USED_IN_CONSTRUCTION)
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/support.py", line 621, in get_primary_max_reads_length
    get_reads_files(dataset_data, log, ignored_types, used_types)]
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/support.py", line 652, in get_max_reads_length
    [len(rec) for rec in itertools.islice(SeqIO.parse(SeqIO.Open(reads_file, "r"), file_type), num_checked)])
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 120, in parse_fastq
    rec_qual = reader.ReadUntillFill(len(rec_seq))
  File "/usr/local/bin/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 61, in ReadUntillFill
    assert (cnt == buf_size)
AssertionError

== Error ==  exception caught: <type 'exceptions.AssertionError'>
```

params.txt
```
Command line: /usr/local/bin/SPAdes-3.14.0-Linux/bin//spades.py -o      /scratch/users/nadine/assembly/spades      --meta  --pe1-1 /scratch/users/nadine/assembly/HHLYTDRXX_113813_1_repaired.fq      --pe1-2 /scratch/users/nadine/assembly/HHLYTDRXX_113813_2_repaired.fq      --pe1-s /scratch/users/nadine/assembly/singletons.fq       --only-assembler        

System information:
  SPAdes version: 3.14.0
  Python version: 2.7.17
  OS: Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic

Output dir: /scratch/users/nadine/assembly/spades
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/scratch/users/nadine/assembly/HHLYTDRXX_113813_1_repaired.fq']
      right reads: ['/scratch/users/nadine/assembly/HHLYTDRXX_113813_2_repaired.fq']
      interlaced reads: not specified
      single reads: ['/scratch/users/nadine/assembly/singletons.fq']
      merged reads: not specified
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/users/nadine/assembly/spades/tmp
  Threads: 16
  Memory limit (in Gb): 169
```
spades is called from a singularity container and I'm running it on a cluster. I've also tried it without the --assembler-only option and I played around with the memory and available cpus, but to no avail. 
The reads were trimmed and cleaned from contaminants, normalized and recalibrated with bbtools before.

What could be the source of the error? Especially I don't know what cnt == buf_size means.

Thank you!
Best,
Nadine

**Comment by olga24912** [comment]
Hi Nadine, 

Thank you for using SPAdes and for your bug report! 

It looks like for some read in "/scratch/users/nadine/assembly/singletons.fq" fastq file the length of sequence and quality are different. Can you take a look at the end of singletons.fq file and check that it is complete?

Best regards, 
Olga

**Comment by Rhinogradentia** [comment]
Hi Olga,

thank you, after omitting the singleton file it worked just fine. At the moment I'm not completely sure what was wrong with the file, but it was too big as well in comparison. 

Best,
Nadine
