### ISSUE TITLE
spades 3.14.1 AssertionError while parse args

### ISSUE THREAD

**Issue by jlli6t** [ablab/spades#511]
Hi developers,

I am using spades 3.14.1.

command line is:
spades.py --pe1-1 fq1 --pe1-2 fq2 -o ./spades --pe1-s fo --pe1-s re -m 20 --isolate --pe-or fr, fr

get error messages below, did't figure out what this error is and what should I do with my comman line, thank you.

Traceback (most recent call last):
  File "/spades/3.14.1/bin/spades.py", line 643, in <module>
    main(sys.argv)
  File "/spades/3.14.1/bin/spades.py", line 581, in main
    cfg, dataset_data, command_line = parse_args(args, log)
  File "/spades/3.14.1/bin/spades.py", line 238, in parse_args
    secondary_filling=False, restart_from=False)
  File "/spades/3.14.1/share/spades/spades_pipeline/options_parser.py", line 1072, in parse_args
    load_processed_dataset, restart_from, options)
  File "/spades/3.14.1/share/spades/spades_pipeline/options_parser.py", line 1012, in postprocessing
    support.check_dataset_reads(dataset_data, (args.only_assembler or args.rna), args.iontorrent, log)
  File "/spades/3.14.1/share/spades/spades_pipeline/support.py", line 689, in check_dataset_reads
    (key, id + 1, reads_library["type"]), log)
  File "/spades/3.14.1/share/spades/spades_pipeline/support.py", line 140, in check_file_not_empty
    if next(reads_iterator, None) is None:
  File "/spades/3.14.1/share/spades/spades_pipeline/common/SeqIO.py", line 117, in parse_fastq
    assert (rec_id[0] == '@')
AssertionError

**Comment by asl** [comment]
Hello

You input should be a valid FASTQ
