### ISSUE TITLE
TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/spades#816]
### Description of bug

```
===== Assembling started.

%d format: a number is required, not str
Traceback (most recent call last):
  File "/ebio/abt3_projects/databases_no-backup/DeepMAsED/version2/resmico-sm/bin/ResMiCo/ResMiCo-SM/.snakemake/conda/7435a6d8fb80d6ef77bec775d8e736eb/bin/spades.py", line 874, in main
    used_K = spades_logic.run_spades(tmp_configs_dir, bin_home, spades_cfg, dataset_data, ext_python_modules_home, log)
  File "/ebio/abt3_projects/databases_no-backup/DeepMAsED/version2/resmico-sm/bin/ResMiCo/ResMiCo-SM/.snakemake/conda/7435a6d8fb80d6ef77bec775d8e736eb/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 308, in run_spades
    run_iteration(configs_dir, execution_home, cfg, log, K, None, True)
  File "/ebio/abt3_projects/databases_no-backup/DeepMAsED/version2/resmico-sm/bin/ResMiCo/ResMiCo-SM/.snakemake/conda/7435a6d8fb80d6ef77bec775d8e736eb/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 164, in run_iteration
    data_dir = os.path.join(cfg.output_dir, "K%d" % K)
TypeError: %d format: a number is required, not str


== Error ==  exception caught: <class 'TypeError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory
```

### spades.log

[spades.log](https://github.com/ablab/spades/files/6899548/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6899538/params.txt)

### SPAdes version

3.13.0

### Operating System

Ubuntu 18.04.5

### Python Version

3.6.13

### Method of SPAdes installation

bioconda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

We believe that this issue was fixed in SPAdes 3.14 and in later versions. We also suggest you to upgrade to the latest SPAdes 3.15.3 as the log clearly contains out-of-memory error.
