### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable' (conds ainstalaltion with py 10)

### ISSUE THREAD

**Issue by SilasK** [ablab/spades#873]
### Description of bug

error reading yaml file pyyaml3 due to python 3.10 mist likely. 

AttributeError: module 'collections' has no attribute 'Hashable'

### spades.log

System information:
  SPAdes version: 3.15.3
  Python version: 3.10.0
  OS: Linux-5.4.104+-x86_64-with-glibc2.27

Output dir: /content/WD/sample2/assembly
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
Traceback (most recent call last):
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/bin/spades.py", line 659, in <module>
    main(sys.argv)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/bin/spades.py", line 599, in main
    print_params(log, log_filename, command_line, args, cfg)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/bin/spades.py", line 327, in print_params
    print_used_values(cfg, log)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/bin/spades.py", line 117, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename))
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/content/databases/conda_envs/91fde30436cb83f9107a310d5f69819a/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

### params.txt

unimportant

### SPAdes version

3.15.3

### Operating System

google colab

### Python Version

3.10

### Method of SPAdes installation

mamba

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Thanks, dup of #863

**Comment by Anushka622001** [comment]
resolve this error

**Comment by MatthiasWilm** [comment]
I am a novel user of Spades. I solved the error by modifying a python script: 
**Operation Environment** 
SPAdes version: 3.15.3
 Python version: 3.10.1
 OS: macOS-12.1-x86_64-i386-64bit

**Edited file:** ... /share/spades/pyyaml3/constructor.py
Line: line 126
**Code was:** `if not isinstance(key, collections.Hashable):`

**Code is:** `if not isinstance(key, collections.abc.Hashable):`

**Reference Source:** 
https://docs.python.org/3/library/collections.abc.html
"New in version 3.3: Formerly, this module was part of the collections module.
...
This module provides abstract base classes that can be used to test whether a class provides a particular interface; for example, whether it is hashable or whether it is a mapping."

**Comment by IronFuturist** [comment]
MattiasWilm your response fixed my issue with AttributeError, thanks.

**Comment by asl** [comment]
This issue was fixed in SPAdes 3.15.4

**Comment by asl** [comment]
No need to modify anything. The fix is included into the latest SPAdes 3.15.4 release

**Comment by asl** [comment]
@CalJMarsh As it was stated above, the fix is included in SPAdes 3.15.4 release. On all platforms Mac included.

**Comment by dhiru16** [comment]
I got the same error but am using the spades 3.15.5

**Comment by asl** [comment]
@dhiru16 Will you please open a new issue attaching all the files requested?
