### ISSUE TITLE
SPAdes won't run after install

### ISSUE THREAD

**Issue by peflanag** [ablab/spades#935]
### Description of bug

I installed SPAdes on a MacBook Pro and when I tried to run it won't. Below is the output:

(base) grainnebrennan@Grainnes-MacBook-Pro ~ % conda activate spades
(spades) grainnebrennan@Grainnes-MacBook-Pro ~ % spades.py -1 /Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R1_001.fastq.gz -2 /Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R2_001.fastq.gz -o /Users/grainnebrennan/WGSAnalysis/spades_output

== Warning ==  output dir is not empty! Please, clean output directory before run.

== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: /Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py	-1	/Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R1_001.fastq.gz-2	/Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R2_001.fastq.gz-o	/Users/grainnebrennan/WGSAnalysis/spades_output	

System information:
  SPAdes version: 3.15.2
  Python version: 3.10.0
  OS: macOS-10.16-x86_64-i386-64bit

Output dir: /Users/grainnebrennan/WGSAnalysis/spades_output
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
Traceback (most recent call last):
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 651, in <module>
    main(sys.argv)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 591, in main
    print_params(log, log_filename, command_line, args, cfg)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 327, in print_params
    print_used_values(cfg, log)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 117, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename))
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
(spades) grainnebrennan@Grainnes-MacBook-Pro ~ %                      

### spades.log

(base) grainnebrennan@Grainnes-MacBook-Pro ~ % conda activate spades
(spades) grainnebrennan@Grainnes-MacBook-Pro ~ % spades.py -1 /Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R1_001.fastq.gz -2 /Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R2_001.fastq.gz -o /Users/grainnebrennan/WGSAnalysis/spades_output

== Warning ==  output dir is not empty! Please, clean output directory before run.

== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: /Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py	-1	/Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R1_001.fastq.gz-2	/Users/grainnebrennan/WGSAnalysis/fastq/M220097_S1_L001_R2_001.fastq.gz-o	/Users/grainnebrennan/WGSAnalysis/spades_output	

System information:
  SPAdes version: 3.15.2
  Python version: 3.10.0
  OS: macOS-10.16-x86_64-i386-64bit

Output dir: /Users/grainnebrennan/WGSAnalysis/spades_output
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
Traceback (most recent call last):
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 651, in <module>
    main(sys.argv)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 591, in main
    print_params(log, log_filename, command_line, args, cfg)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 327, in print_params
    print_used_values(cfg, log)
  File "/Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py", line 117, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename))
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/grainnebrennan/miniconda3/envs/spades/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
(spades) grainnebrennan@Grainnes-MacBook-Pro ~ %                      

### params.txt

Command line: /Users/grainnebrennan/miniconda3/envs/spades/bin/spades.py	-1	/Users/grainnebrennan/WGSAnalysis/fastp_output/M220097_R1.fq.gz	-2	/Users/grainnebrennan/WGSAnalysis/fastp_output/M220097_R2.fq.gz	-o	/Users/grainnebrennan/WGSAnalysis/spades_output/M220097	

System information:
  SPAdes version: 3.15.2
  Python version: 3.10.0
  OS: macOS-10.16-x86_64-i386-64bit

Output dir: /Users/grainnebrennan/WGSAnalysis/spades_output/M220097
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:

### SPAdes version

v3.15.2

### Operating System

macOS Montery 12.2.1

### Python Version

3.10.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is a known issue that was fixed in SPAdes 3.15.4. Consider upgrading
